.htaccess, SL/.htaccess, bin/mozilla/.htaccess, config/.htaccess, locale/.htaccess, scripts/.htaccess, t/.htaccess, templates/.htaccess
See also: https://httpd.apache.org/docs/2.4/upgrading.html
=> Update .htaccess for Apache 2.4 to avoid mod_access_compat dependency

sql/Pg-upgrade2/accounts_tax_office_leonberg.sql
See also:
- http://www.fa-leonberg.de/pb/,Lde/Startseite
- http://www.fa-leonberg.de/pb/,Lde/Startseite/Ihr+Finanzamt/Bankverbindungen
=> Reflect changed data of tax office Leonberg (since 2018)

templates/print/marei/Readme.md, templates/print/marei/bin_list.tex, templates/print/marei/check.tex, templates/print/marei/credit_note.tex, templates/print/marei/deutsch.tex, templates/print/marei/english.tex, templates/print/marei/ic_supply.tex, templates/print/marei/ic_supply_EN.tex, templates/print/marei/insettings.tex, templates/print/marei/invoice.tex, templates/print/marei/kiviletter.sty, templates/print/marei/kivitendo.sty, templates/print/marei/letter.tex, templates/print/marei/pick_list.tex, templates/print/marei/proforma.tex, templates/print/marei/purchase_delivery_order.tex, templates/print/marei/purchase_order.tex, templates/print/marei/receipt.tex, templates/print/marei/request_quotation.tex, templates/print/marei/requirement_spec.tex, templates/print/marei/sales_delivery_order.tex, templates/print/marei/sales_order.tex, templates/print/marei/sales_quotation.tex, templates/print/marei/statement.tex, templates/print/marei/zahlungserinnerung.tex, templates/print/marei/zahlungserinnerung_invoice.tex
Erweiterung für farbige Tabellen, Layoutanpassung sowie Hinweise auf Mechanismen zur manuelle platzierung von Elementen im Brieflayout. 
Darüber hinaus hab ich jetzt im Auftrag die Einrückungen auf spaces umgestellt.
=> LaTeX colored tables

SL/DB/MetaSetup/InvoiceItem.pm, SL/IC.pm, SL/IO.pm, SL/IR.pm, bin/mozilla/io.pl, bin/mozilla/ir.pl, js/kivi.io.js, sql/Pg-upgrade2/add_charts_and_taxkey_to_invoice_items.sql, sql/Pg-upgrade2/add_tax_chart_type_to_invoice_items.sql, t/workflow/invoice_to_reclamation.t, templates/design40_webpages/ir/form_header.html, templates/design40_webpages/ir/update_taxes.html, templates/webpages/ir/form_header.html, templates/webpages/ir/update_taxes.html
Unsere manuellen Anwendertests hatten noch drei Fehler gefunden und laufen jetzt durch.
Demnach Freigabe für den Standard.
=> Superimpose charts and tax in purchase invoice items

templates/print/marei/kiviletter.sty
Da ist die im Januar besprochene Anpassung der extraDescription. @wernerhahn wollte das testen.
=> \ after extradescription  only if hmode

bin/mozilla/io.pl
=> Zwischensumme beim Umsortieren von Belegpositionen mit sortieren

SL/Controller/ZUGFeRD.pm, bin/mozilla/ap.pl, js/kivi.ZUGFeRD.js, templates/design40_webpages/ap/form_header.html, templates/design40_webpages/zugferd/form.html, templates/webpages/ap/form_header.html, templates/webpages/zugferd/form.html
=> ZUGFeRD: speicher ZUGFeRD-Datei zur erstellten Kreditorenbuchung

bin/mozilla/rp.pl
=> Bericht: SuSa: Abteilungs- u. Projektfilter in hiddens

bin/mozilla/ir.pl, bin/mozilla/is.pl, templates/design40_webpages/ir/form_header.html, templates/design40_webpages/is/form_header.html, templates/webpages/ir/form_header.html, templates/webpages/is/form_header.html
=> FIX: 'Buchen auf' in EK/VK Rechnungen richtig vorbelegen

templates/design40_webpages/report_generator/html_report.html
=> Design4.0: Fix Zeilenumbrüche in Reportgenerator Template reduzieren

bin/mozilla/is.pl
behebt #621 (redmine) und
behebt #622 (redmine)
=> ckeditor5: update der javascripte in bin/mozilla/is.pl

templates/print/marei/kiviletter.sty
=> adjust PricingTabular Header box spacing

templates/design40_webpages/order/tabs/_purchase_delivery_order_item_selection.html, templates/webpages/order/tabs/_purchase_delivery_order_item_selection.html
Indexierung war im Template um 1 verschoben.
=> FIX(625): EK-Auftrag → EK-Lieferschein: Wähle die korrekten Artikel

SL/OE.pm
Die Häkchen waren auf der EK-Seite da, aber diese wurde in der SQL-Abfrage nicht berücksichtigt.
=> Offene Restbeträge optional auch in Lieferanten-Auftragsbericht anzeigen

SL/Controller/CustomerVendor.pm, SL/Controller/DeliveryOrder.pm, SL/Controller/Order.pm, SL/Controller/Reclamation.pm, SL/Presenter/CustomerVendor.pm, bin/mozilla/ap.pl, bin/mozilla/ar.pl, js/kivi.CustomerVendor.js, js/kivi.DeliveryOrder.js, js/kivi.Order.js, js/kivi.Reclamation.js, templates/design40_webpages/ap/form_header.html, templates/design40_webpages/ar/form_header.html, templates/design40_webpages/customer_vendor/test_page.html, templates/design40_webpages/delivery_order/tabs/basic_data.html, templates/design40_webpages/ir/form_header.html, templates/design40_webpages/is/form_header.html, templates/design40_webpages/order/tabs/basic_data.html, templates/design40_webpages/reclamation/tabs/basic_data.html, templates/webpages/ap/form_header.html, templates/webpages/ar/form_header.html, templates/webpages/customer_vendor/test_page.html, templates/webpages/delivery_order/tabs/basic_data.html, templates/webpages/ir/form_header.html, templates/webpages/is/form_header.html, templates/webpages/order/tabs/basic_data.html, templates/webpages/reclamation/tabs/basic_data.html
Hier mal ein Vorschlag mit den Details im präsenter eingebaut.
Finde das sieht dann im template schon einiges besser aus.
Es geht um diese details hier:
Die action habe ich in die SL/Controller/CustomerVendor.pm eingefügt, die kommt aber an mehreren stellen vor wo man sie dann löschen könnte.
Was meint ihr dazu?
Es fehlt noch Dokumentation im POD sowie alte templates, wobei ich nicht weiß ob sich das noch lohnt da was zu ändern. ;)
=> 20230929 wip customer vendor details presenter

SL/Controller/CsvImport/CustomerVendor.pm
=> S:C:CsvImport/CustomerVendor: Lieferanten haben keine Preisgruppe

SL/Controller/Reclamation.pm
Typenvergleich korrigiert
Behebt (teilw.): Fehler #648
=> Fix Verkauf/Einkauf -> Berichte -> Verkaufs/Einkaufsreklamationen

templates/print/marei/Readme.md, templates/print/marei/bin_list.tex, templates/print/marei/check.tex, templates/print/marei/credit_note.tex, templates/print/marei/ic_supply.tex, templates/print/marei/ic_supply_EN.tex, templates/print/marei/invoice.tex, templates/print/marei/kiviletter.sty, templates/print/marei/letter.tex, templates/print/marei/pick_list.tex, templates/print/marei/proforma.tex, templates/print/marei/purchase_delivery_order.tex, templates/print/marei/purchase_order.tex, templates/print/marei/purchase_quotation_intake.tex, templates/print/marei/purchase_reclamation.tex, templates/print/marei/receipt.tex, templates/print/marei/request_quotation.tex, templates/print/marei/sales_delivery_order.tex, templates/print/marei/sales_order.tex, templates/print/marei/sales_quotation.tex, templates/print/marei/sales_reclamation.tex, templates/print/marei/statement.tex, templates/print/marei/supplier_delivery_order.tex, templates/print/marei/zahlungserinnerung.tex, templates/print/marei/zahlungserinnerung_invoice.tex
wie besprochen, @jbueren  - guck mal bitte, ob ich alle Dateitypen erwischt habe, die Zuordnung bzgl. der Dateinamen ist nicht immer ganz so einfach. 
Ich hab es außerdem gegenüber dem, was du bei $KUNDE gemacht hattest, die Struktur so umgestellt, dass auf die Variable nur einmal geprüft wird, müsste ja auch gehen, halte ich für übersichtlicher.
=> billing_address support + color-only-structure

templates/design40_webpages/csv_import/report.html
=> Design4.0: Csv-Import-Report: auch erste Datenzeile anzeigen

SL/Controller/TopQuickSearch/GLTransaction.pm
=> TopQuickSearch: GL Suche Verkaufrechnungen auch vom Anfang suchen

SL/Controller/Invoice.pm, SL/DB/EmailJournalAttachment.pm
nutze 'invoice' anstelle von 'general_ledger'
=> FIX: Objekttype für altes Webdav von Debitorenbuchung angepasst

t/Support/Integration.pm, t/fxtransaction/ap_transactions.t
Auf Anfrage von Jan: Die Routinen zu roundtrip tests ausgelagert nach t/Support/Integration.pm
=> 2024 integration test helper

SL/BackgroundJob/ShopPartMassCreate.pm, doc/changelog
Habe für unsere Anwendung bei revamp einen Background Job erstellt.
Könnte von mir aus in den master.
Könnte auch für andere nützlich sein und ist ja relativ unabhängig von anderen Sachen. Wobei es je nach fall halt allenfalls eine individuelle Anpassung dann braucht.
LG, Cem
=> Neuer Backgroundjob zum Massen-generieren von Shop Artikeln aus Artikeln

sql/Pg-upgrade2/steuerfilterung.pl
Neue Schweizer Mehrwertsteuersätze eintragen.
Behebt: Fehler #671
=> Fix: dbupgrade Skript steuerfilterung.pl

SL/PriceSource.pm
Ansonsten fehlt die ID für die makemodel Abfrage und Rose wirft einen harten SQL Fehler
=> Preisquelle: Alle Parameter prüfen

templates/design40_webpages/ar/form_header.html
behebt #734
Mit javascript jetzt die ID anstatt den Namen angesprochen, damit das richtige Feld belegt wird
=> Debitorenbuchungen input eine ID gegeben, Zahlenformartierungen

SL/DB/BankTransaction.pm, t/bank/bank_transactions.t
Eigentlich sollte das review Jason machen. Der war ja auch bei dem Workshop dabei und da sind drei einfache aber wichtige Pattern drin. 13.01. ?
=> 202411 match end to end bt

templates/print/marei/credit_note.tex, templates/print/marei/invoice.tex, templates/print/marei/proforma.tex, templates/print/marei/statement.tex, templates/print/marei/zahlungserinnerung.tex, templates/print/marei/zahlungserinnerung_invoice.tex
Da war eine Abfrage falsch. Die würde ich damit gerne korrigieren. Wäre cool, wenn jemand das mal testen könnte. Ansonsten mach ich das selber, sobald ich Zeit finde.
=> marei - bugfix: fix check for billing_address_department_

templates/design40_webpages/common/_send_email_dialog.html
=> Fix Anhänge bei Emailversand immer angehakt. Nur Design 4.0

templates/design40_webpages/part/_assortment.html, templates/webpages/part/_assortment.html
Im Sortiment konnte man nicht mit Enter etwas hinzufügen, sondern nur per Click auf den Button
=> Fix Maske Sortiment Add_item mit Enter

templates/design40_webpages/order/tabs/_item_below_input.html, templates/webpages/order/tabs/_item_below_input.html
Das kam mit dem Umbau von diesem verschiebbaren Item Input wieder rein gekommen.
Vgl. Commit 29038bd
=> templates: vergessenes feature_experimental_assortment entfernt

SL/Controller/Reclamation.pm, js/kivi.Reclamation.js, templates/design40_webpages/reclamation/tabs/basic_data/_row.html, templates/webpages/reclamation/tabs/basic_data/_row.html
sed -i s/reclamationitem_ids/reclamation_item_ids/g `git grep -l reclamationitem_ids`
sed -i s/reclamation_items_ids/reclamation_item_ids/g `git grep -l reclamation_items_ids`
Behebt u.a. Probleme beim Aktualisieren der Pos.-Zeilen aus den Stammdaten. Behebt #758 (redmine)
=> Reklamation: Typo in form-Variable reclamation_item_ids

templates/print/marei/english.tex, templates/print/marei/proforma.tex, templates/print/marei/purchase_order.tex, templates/print/marei/purchase_quotation_intake.tex, templates/print/marei/purchase_reclamation.tex, templates/print/marei/sales_order.tex, templates/print/marei/sales_reclamation.tex, templates/print/marei/supplier_delivery_order.tex
kleinere Dinge, die mir aufgefallen sind und die ich direkt behoben habe
(siehe commit messages)
=> Druckvorlagen marei Verbesserungen

SL/DB/Helper/FlattenToForm.pm
=> FlattenToForm mandator_id und mandate_date_of_signature aufgenommen

doc/dokumentation.xml
Den PR von Roman aus dem März nochmal in neu, plus Hinweis auf minimale Perl und Postgres Version
=> Doku für PR #461 neu gebaut und ergänzt

SL/DN.pm, bin/mozilla/dn.pl, doc/changelog, templates/design40_webpages/dunning/search.html
Gesamtsumme der Beträge und Zwischensummen (optional) im Mahnungsbericht anzeigen. SIehe auch issue #591 .
=> 20250826 feat dunning subtotals

SL/DB/Part.pm, bin/mozilla/wh.pl, doc/changelog
Zwei Kleinigkeiten das Lager betreffend:
- Preisfaktor berücksichtigen beim Warenbestand im Artikelstamm
- Im Lagerjournal Artikel anklickbar (Link)
=> 202509 enhance wh reports
