kivitendo/kivitendo-erp

- doc/UPGRADE
List::UtilsBy was introduced in 3.2.0, but UPGRADE didn't mention it and 'scripts/installation_check.pl' checks for it ...
> add missing List::UtilsBy to list of new perl modules in UPGRADE/3.2.0

- bin/mozilla/ap.pl
Es wurde der Wert der Debitorenbuchung-Änderbarkeit statt der Kreditorenbuchung-Änderbarkeit aus der Mandantenkonfiguration abgefragt.
> Bug-Fix: Kreditorenbuchung-Änderbarkeit

- SL/BackgroundJob/CreatePeriodicInvoices.pm
Auch mit `definierter global_bcc` werden `wiederkehrende Rechnungen` nicht an die `global_bcc` versendet. Dies funktioniert nur mit `normal manuell` generierten Rechnungen, Aufträgen ... etc.
Da `wiederkehrende Rechnungen` auch an den `global_bcc` versendet werden sollen, habe ich versucht diesen Mißstand zu beheben.
Ich hätte auch gerne das `Formular` für `wiederkehrende Rechnungen` angepasst, damit man dort _explizit_ einen `BCC-Empfänger` definieren kann. Aber dafür reichen meine kivitendo Kenntnisse derzeit noch nicht ganz aus. Auch sind meine perl Kenntnisse eher dürftig ...
Wäre schön, wenn Ihr mir Tips geben könntet, welche Dateien ich dafür anfassen müßte. Dann würde ich versuchen die `wiederkehrenden Rechnungen` dahingehend zu verbessern.
Danke und Gruß
Chris
> fehlendes BCC(global_bcc) in CreatePeriodicInvoices.pm(_email_invoice) hinzugefügt

- SL/ShopConnector/Shopware.pm
Scheint seit Shopware 5.2 notwendig zu sein, damit der Artikel im Frontend erscheint.
s. https://forum.shopware.com/discussion/39006/artikel-nach-import-ueber-rest-api-im-frontend-nicht-sichtbar
> Neu angelegte Artikel in Shopware aktivieren.

- doc/dokumentation.xml
- doc/html/ch03s10.html
Ansonsten werden Pfade mit Leerzeichen zu einzelnen Argumenten.
> quoten von Argumentlist in shellscript

- templates/print/marei/kiviletter.sty
Ich suche noch eine Möglichkeit alle Varianten möglichst automatisiert zu Testzwecken zu erzeugen, falls da jemand einen Tipp für mich hat, wäre das super. 
Ansonsten Entfernen die Updates ein paar Leerzeilen, die durch die Generierung des TeX-Codes erzeugt werden und ermöglicht es die Reihenfolge der Tabellenspalten sowie deren Ausgabe zu ändern.
> Neuimplementierung und Feature Erweiterung für die Aktualisierten LaTeX Templates

- templates/print/marei/kiviletter.sty
add missing `\par` if in horizontal mode.
> marei: fix bug concerning misisng linebreaks in \FakeTable

- templates/print/marei/Readme.md
- templates/print/marei/insettings.tex
- templates/print/marei/kiviletter.sty
ersatz für 000908d73c032707d8d02cd5b4c768ea29aa4b78 um die standardwährung in der insettings.tex festzulegen.
> replace 000908d73c032707d8d02cd5b4c768ea29aa4b78 - change default currency setting for marei

- SL/BackgroundJob/ValidityTokenCleanup.pm
- SL/DB/Helper/ALL.pm
- SL/DB/Helper/Mappings.pm
- SL/DB/Manager/ValidityToken.pm
- SL/DB/MetaSetup/ValidityToken.pm
- SL/DB/ValidityToken.pm
- bin/mozilla/is.pl
- locale/de/all
- sql/Pg-upgrade2/validity_tokens.sql
- templates/webpages/is/form_header.html
Ziel: verhindern, dass eine noch nicht gebuchte Rechnung durch
Verwendung des »Zurück«-Buttons im Browser mehrfach gebucht werden
kann.
Implementation: Beim Neuanlegen einer Rechnung wird ein einmaliges
Gültigkeitstoken mit einem Scope (»Verkaufsrechnung buchen«)
erzeugt. Dieses hat eine Laufzeit von 24h. Es wird als Hidden-Variable
im Formular mitgeschleift, sofern noch keine Datenbank-ID existiert,
die Rechnung also noch nicht gebucht wurde.
Wird die Rechnung gebucht, so wird zuerst überprüft, ob das vom
Browser mitgeschickte Token noch gültig ist:
1. ob es das Token mit demselben Scope in der Datenbank noch gibt
2. ob das Ablaufdatum des Tokens noch nicht erreicht ist
Falls ja, wird die Rechnung gebucht und das Token aus der Datenbank
und dem Formular entfernt. Es ist somit entwertet …
> proof of concept: Formular-Gültigkeit beim Buchen von Verkaufsrechnungen

- scripts/installation_check.pl
Behebt folgende Warnmeldung:
```
Unrecognized escape \R passed through at scripts/installation_check.pl line 163.
```
> fehlendes Escaping im check-Skript ergänzt

- SL/Template/LaTeX.pm
wie mit @mbunkus besprochen hier die mini Anpassung bezüglich der Ersetzung.
> LaTeX switch from `\n\n` to `\par` in replacements of user input

- templates/print/marei/kiviletter.sty
löst außerdem den Bug mit falschen einzügen auf der Linken seite von Listen innerhalb der `\ExtraDescription`.
> marei: eigene spaltentypen auch bei der Verarbeitung in PricingTabular verarbeiten

- t/db_helper/record_links.t
Dieser Test schlägt manchmal fehl, da die Reihenfolge der zurückgelieferten Links nicht stabil ist.
Die Frage ist hier, ob der Helper die Links in der Reihenfolge der angegebenen Ids zurückgeben soll (also der Helper kaputt ist), oder ob die Reihenfolge unbestimmt ist (also der Test falsch ist).
Deshalb: TODO.
Refs #571 (redmine)
> record_links.t: batch-Test als TODO markieren

- templates/design40_webpages/is/form_header.html
- templates/design40_webpages/order/tabs/basic_data.html
- Angebot und Auftrag: Input Feld verkleinert, damit alles auf einer Zeile Platz findet
- Rechnung: Umrechnungskurs direkt unter der Waehrung plaziert
> Design40 Korrektur bei der Darstellung des Umrechnungskurses

- templates/print/marei/credit_note.tex
- templates/print/marei/inheaders.tex
- templates/print/marei/invoice.tex
- templates/print/marei/kiviletter.sty
- templates/print/marei/proforma.tex
- templates/print/marei/purchase_delivery_order.tex
- templates/print/marei/purchase_order.tex
- templates/print/marei/purchase_reclamation.tex
- templates/print/marei/request_quotation.tex
- templates/print/marei/sales_delivery_order.tex
- templates/print/marei/sales_order.tex
- templates/print/marei/sales_quotation.tex
- templates/print/marei/sales_reclamation.tex
- templates/print/marei/statement.tex
- templates/print/marei/supplier_delivery_order.tex
- templates/print/marei/zahlungserinnerung.tex
- templates/print/marei/zahlungserinnerung_invoice.tex
Es gibt aktuell einen Bug, der verhindert, dass bei farbigen Tabellen der Umbruch zwischen der description und der longdescription richtig gesetzt wird. Der PR soll daran etwas ändern. Bräuchte aber ein paar kivitendo Nutzer*innen die das testen um sicherzustellen, dass es alle Anwedungsfälle abdeckt.
> colored tables extra description

- templates/print/marei/kiviletter.sty
behebt den syntax error in #115
> marei: fix syntax error

- SL/BackgroundJob/SelfTest.pm
Sonst wird auch der Platzhalter (#1) nicht ersetzt.
> SelfTest: Fehlermeldung beim E-Mail-Versand übersetzen.

- templates/design40_webpages/do/form_header.html
- Hier war zweimal notes angesprochen, statt intnotes.
- Position unter Bemerkungen, wie in den anderen Masken
> design40: Interne Bemerkungen bei Lieferschein repariert.

- SL/AP.pm
- SL/Form.pm
- bin/mozilla/ap.pl
... dennoch Steuerschlüssel für den DATEV-Export korrekt setzen
> reverse Charge Steuerschlüssel 94, keine Steuerbuchung in acc_trans

- SL/AM.pm
Das sollte zwar nicht vorkommen, aber es gibt auch in neu angelegten SKR03/04-Datenbanken Konten, die keinen Eintrag in taxkeys haben. Diese lassen sich dann nicht editieren/korrigieren.
Beim Speichern der Konten wird schon (und wurde vorher auch) überprüft, ob ein gültiger Steuerschlüssel vorliegt.
Evtl. sollte auch noch ein Upgrade-Skript für diese Konten gebaut werden.
> Konten auch ohne Eintrag in taxkeys bearbeiten können.

- SL/Controller/CustomerVendor.pm
- SL/DB/Business.pm
- SL/DB/PartsGroup.pm
- SL/DB/Pricegroup.pm
Behebt #114 (redmine) bzw. die Reste davon.
Artikel löschen können wurde schon gelöst.
> In Preisregeln benutze Objekte nicht löschen können.

- templates/design40_webpages/bank_transactions/tabs/automatic.html
So, hier noch der branch/pull request zu den design fixes, wie mit Jan/Enrique besprochen.
Der erste commit sollte mal das horizontale Scrollen beim Kontoauszug verbuchen fixen.
Beim vertikalen scrollen geht immer noch der Untertitel mit. Das wäre noch zu fixen ;)
Weitere commits könnten ja dann, vor zu, hier auf diesen branch.
LG
Cem
> Design4.0: Diverse Fixes

- templates/design40_webpages/oe/search.html
- templates/webpages/oe/search.html
Bestätigungsdatum statt Auftragsdatum
> Lieferantenauftragsbestätigung: Bericht: Datumsfilter deutlicher benannt

- SL/Controller/ListTransactions.pm
- doc/changelog
- locale/de/all
- locale/en/all
Analog zum CSV export.
Changelog aktualisiert.
> Berichte Buchungsliste Export aller Konten als PDF (ZIP) ermöglichen

- js/kivi.js
- templates/design40_webpages/common/_send_email_dialog.html
- templates/webpages/common/_send_email_dialog.html
Ckeditor5 übernimmt standardmäßig nicht die Höhe des unterliegenden texarea Elements.
Der initializer Code versucht diese Information zu übergeben, kann aber aus dem "rows" Attribute nicht einfach die Höhe ableiten, und leider auch nicht auf die Renderinformationen von sowohl dem textare als auch dem Ckeditor zugreifen.
Stattdessen wird als Heuristik ~30px pro Zeile angenommen.
> Ckeditor5: P.textarea(..., rows=x) Funktion wieder hergestellt

- SL/Controller/DeliveryOrder.pm
Nutze `module => 'DO'` für SL::DB::Shipto bei Lieferscheinen
> FIX: S:C:DeliveryOrder: individuelle Lieferadresse richtig speichern

- SL/IMAPClient.pm
Soll fehler beim E-Mail-Import beheben:
```
do_transaction() failed - Unknown encoding 'ISO-8859-15"; boundary="TV9DrMVkMaq=_bmSputGDOgvpTUuPA7gHZ' at /var/www/kivitendo-erp/SL/IMAPClient.pm line 262.
```
> IMAPClient: FIX: gültige Zeichen für Zeichensatzname verwenden

- templates/design40_webpages/common/toggle-buttons-for-wrapper.html
- templates/design40_webpages/generic/toggle_wrapper.html
window.onload anstatt document.ready verwenden. Dieses wartet bis das layout vollständig geladen ist und somit wird die richtige Höhe für den wrapper verwendet.
Behebt: #688
> design40: Toggle Wrapper in Belegen, Höhe korrigiert

- SL/Controller/BackgroundJob.pm
- SL/Controller/BackgroundJobHistory.pm
- SL/DB/BackgroundJob.pm
- SL/DB/MetaSetup/BackgroundJob.pm
- SL/DB/MetaSetup/BackgroundJobHistory.pm
- doc/changelog
- sql/Pg-upgrade2/add_description_to_backgroundjob_and_backgroundjobhistory.sql
- templates/design40_webpages/background_job/form.html
- templates/design40_webpages/background_job/list.html
- templates/design40_webpages/background_job_history/_filter.html
- templates/design40_webpages/background_job_history/list.html
- templates/design40_webpages/background_job_history/show.html
- templates/webpages/background_job/form.html
- templates/webpages/background_job/list.html
- templates/webpages/background_job_history/_filter.html
- templates/webpages/background_job_history/list.html
- templates/webpages/background_job_history/show.html
- templates/webpages/failed_background_jobs_report/email.txt
- templates/webpages/task_server/failure_notification_email.txt
Extra Beschreibung bei den Backgroundjobs, sodass sich verschiedene Email Importe oder TimeConverters besser auseinander halten lassen können
> 202405 feat description in backgroundjob

- templates/webpages/delivery_order/tabs/_row.html
siehe auch: 0e6c7d395139848cf55c0147909394b3ee51ba94
("FIX: DeliveryOrder: Preisgruppen Source in Template speichern")
> DeliveryOrder: FIX: altes Design: Preisgruppen Source speichern

- templates/design40_webpages/simple_system_setting/list.html
Im HTML-Template war die Klassen 'dragdrop' nicht (immer) vorhanden, da das Schlüsselwort 'class' mehrfach angegeben wurde.
Behebt #705 (redmine).
> design4.0: SimpleSystemSettings: Listen umsortieren können

- bin/mozilla/is.pl
- templates/design40_webpages/delivery_order/tabs/basic_data.html
- templates/design40_webpages/order/tabs/basic_data.html
- templates/design40_webpages/reclamation/tabs/basic_data.html
- templates/webpages/delivery_order/tabs/basic_data.html
In den Masken von Design40 wurde 'Steuer im Preis inbegriffen' falsch gerendert (Auftrag, Reklamation). Bei Lieferschein wurde das Hidden-Feld vergessen und somit nicht mitgenommen. Bei Rechnung wurde der Wert nicht dem Template übergeben und war somit immer bei default leer, aber für die Berechnung wurder der richtige Wert aus den Einstellung genommen.
> 202408 fix taxincluded is lost in template

- SL/AR.pm
- SL/OE.pm
- SL/VK.pm
Ab psql Version 15 oder 16 gibt es einen Fehler, wenn sowas abgfragt wird: SELECT * FROM oe WHERE 1 = 1AND ...;
(ERROR:  trailing junk after numeric literal at or near "1A")
Das passierte in älteren Versionen nicht, deshalb sind die fehlenden Leerzeiche wohl nie aufgefallen.
> Berichte Angebote/Aufträge,Rechnungen,VK: Leerzeichen in SQL-Abfrage

- bin/mozilla/do.pl
Eigene Aufträge werden hier auch erstmal ignoriert, sind also auch nicht anklickbar.
> Kein Link zu Aufträgen in Lieferschein-Bericht, wenn kein Recht.

- menus/user/00-erp.yaml
Verwaiste Einträge "Modul-Übersicht" und "Modul aktivieren" zu "Module" aus dem Reiter "Programm" entfernt.
Lokal ohne Fehler getestet
> Ungenutzt Menüeinträge zu Modulen aus dem Reiter "Programm" entfernt

- SL/ShopConnector/Shopware6.pm
Behebt: Fehler #718
----------
Siehe: https://www.kivitendo.de/redmine/issues/718
> FIX: shopware6 connector: Check API Zeigt Fehlermeldung nicht an

- SL/BackgroundJob/ShopPartMassCreate.pm
Löschen der Bilder funktionierte so nicht, die Dateien bleiben im Dateisystem erhalten aber der Datenbank Eintrag wird gelöscht. Dies müsste im File Management System angeschaut werden. Für den Moment überspringe ich die Dateien hier.
> Backgroundjob: ShopPartMassCreate Existierende Bilder überspringen

- SL/ShopConnector/Shopware6.pm
Siehe auch:
https://forum.shopware.com/t/produkt-bilder-uber-api-hochladen/60780/5
Behebt: Fehler #686
------------------------------
Also bei mir behebt dieser Code das Problem ^^ mit shopware v6.6.
Aber es wäre vielleicht gut wenn das sonst mal noch jemand testen könnte. Ältere Shopware Version kann ich jetzt gerade nicht mehr testen da wir umgestellt haben, aber soweit ich das in der API Dokumentation sehe, sollte das eigentlich auch gehen.
https://www.kivitendo.de/redmine/issues/686
> FIX: shopware6 connector: Bilder Upload für Shopware >= v6.6 Beheben

- config/kivitendo.conf.default
- doc/dokumentation.xml
Um Mergekonflikte zu vermeiden, wird das PDF und die HTML-Doku erst später eingecheckt.
> 202412 doku installation logpfad

- SL/Controller/DeliveryOrder.pm
- SL/Controller/Order.pm
- SL/Controller/Reclamation.pm
Behebt im Auftragsbericht unter Aktionen->Neuer Auftrag Fehler:
`Can't call method "is_empty" on an undefined value...`
> 202502 fix is empty on undefined value

- SL/Controller/DeliveryOrder.pm
Wurde falsch auf Artikel des Transfers zugegriffen
> FIX: DeliveryOrder: Ohne Prüfung auf Bestand

- SL/Controller/CsvImport/BaseMulti.pm
Siehe auch commit 6410ae9fc53e8501b21038c41005e39831020f5f CsvImport: dateformat Unterstützung
Behebt #754 (redmine).
> CsvImport: Datumsformat bei Multiplex-Importen berücksichtigen

- SL/Controller/Admin.pm
- config/kivitendo.conf.default
- sql/Pg-upgrade2-auth/set_all_users_to_design40.sql
Wie in letzter Partnerkonferenz besprochen:
Alle Benutzer auf design4.0 umstellen per DB-Upgrade
> DB: alle Benutzer auf Stilvorlage design40 setzen

- SL/Controller/Order.pm
Dazu: Beschreibung wird vorbelegt auf Übersetzung in der Sprache, in welcher der Beleg erfasst wird. Nutzer kann das Feld ändern. Wert wird dann übernommen.
Behebt Fehler #499
(Der Fehler bezieht sich nur auf Order, grundsätzlich ist das auch relevant für Lieferschein, Reklamation: #554 #575, dort allerdings im PartPicker, daher hier berücksichtigt.)
Arbeit gemeinsam mit Max
> S:C:Order: Beschreibung übernehmen bei Hinzufügen neuer Artikel

- SL/Controller/BankTransaction.pm
- SL/DB/Helper/Payment.pm
- SL/DB/Invoice.pm
- SL/DB/PurchaseInvoice.pm
- t/bank/bank_transactions.t
Behebt Fehler #699: Der Skonto-Betrag wird mit dem falschen Vorzeichen verbucht.
Tests hinzugefügt.
> 202503 Skontobuchung Einkaufsgutschrift Fix #699

- SL/Controller/DeliveryOrder.pm
Wichtiger Commit, den wir leider in der Sprintwoche vergessen haben zu mergen, ohne den geht das auslagern über Standardlager nicht.
> FIX: S:C:DeiveryOrder: Zyklische Referenzen in Rose-Object

- SL/SEPA/XML.pm
Der Sequenztyp `OOFF` = `one-off` ist nur für Mandate gedacht, die nur eine einzige Verwendung, nur einen einzigen Einzug zulassen. Für mehrfach verwendbare Mandate gibt es hingegen die Sequenztypen `FRST` = `first` (für erstmalige Verwendung), `RCUR` = `recurring` (für folgende Verwendungen) und `FNAL` = `final` (letzte Verwendung).
Der SEPA-Standard erlaubt explizit die Verwendung von `RCUR` auch für die allererste Verwendung. Daher nutzen wir in kivitendo ausschließlich `RCUR` & tracken nicht, ob ein Mandat schon verwendet wurde.
> SEPA-Bankeinzüge: Sequenz-Typ RCUR nutzen

- doc/dokumentation.xml
Wie im Austausch mit Niklas besprochen ein PR zur Doku. Mein Vorschlag ist, den ganzen Absatz zu entfernen. Zum einen kann auf Systemen, auf denen eine Neuinstallation von Kivitendo zu erwarten ist, heutzutage davon ausgegangen werden, dass UTF8 zum Enkodieren benutzt wird. Der gegenteilige Fall ist zum Anderen nicht besonders gut beschrieben.
* `--locale` funktioniert nicht auf jedem System einfach so; wurden die locales nicht generiert, dann bricht pg_createcluster ab, und meiner Erinnerung nach war nicht so offensichtlich, warum
* `pg_createcluster` ist ein distrospezifischer Wrapper um initdb
* andere locales als C und en_US (oder vielleicht auch andere en_*) werfen bei meinen Installationen im Betrieb jede Menge Warnungen `WARNING:  could not determine encoding for locale …
> Absatz mit pg_createcluster ist veraltet?

- SL/ZUGFeRD.pm
> ZUGFeRD: fix xml extract wenn der Dateistream in einem indirekten pdf dict liegt

- templates/design40_webpages/customer_vendor/tabs/price_list.html
Zuvor wurde das `<div class="wrapper">` in js/kivi.CustomerVendor.js entfernt beim Nachladen der Daten. Dies hatte zur Folge, dass der seitliche Abstand, den der Wrapper bewirkt, bei der Preisliste fehlte.
Hier die relevante stelle aus js/kivi.CustomerVendor.js:
```
if (ui.newPanel.attr('id') == 'price_list') {
ns.get_price_report('#price_list',
"controller.pl?action=CustomerVendor/ajax_list_prices&id="
+ $('#cv_id').val() + "&db=" + $('#db').val()
+ "&callback=" + $('#callback').val());
}
```
Repariert mit diesem Commit:
Zuvor sah es so aus:
> design4.0: Preisliste (Kunden/Lieferanten): setze CSS wrapper

- SL/DB/Helper/ZUGFeRD.pm
Neue Version vom GLN/EAN Export, diesmal CIUS kompatibel.
- GLN jetzt in ram:ID von Seller/BuyerTradeParty (statt Customernumber und Leitwegid)
- EAN jetzt im ram:SellerAssignedID (statt Partnumber)
Es ist sehr schade, dass CIUS die dafür vorgesehenen Felder nicht akzeptiert. Wenn wir das doch nochmal brauchen, müssen wir dafür ein neuen Profil aufmachen.
Zusätzlich habe ich auch noch die currencyId aus ram:ApplicableTradePaymentDiscountTerms entfernt, die wurde auch noch angemeckert.
> 2025 zugferd export gln ean 2

- bin/mozilla/wh.pl
Erzeugnisse ohne Artikel können beim CSV Import entstehen. Für sie liefert der Schritt "Erzeugnis fertigen" nun eine für Anwender verständliche Fehlermeldung.
> Fertigen eines Erzeugnisses ohne Artikel abfangen

- SL/IC.pm
- bin/mozilla/ic.pl
- templates/design40_webpages/ic/search.html
Diese Änderung erlaubt, im Artikelbericht auch die Buchungsgruppe auszugeben.
Ein Kunde verwendet dies, um per PDF-Export aus dem Artikelbericht eine Preisliste für seine Kunden zu erzeugen, welche die Umsatzsteuerklasse (7% / 19%) beinhaltet. Zusammen mit der bereits vorhandenen Filterfunktionalität ist dies recht flexibel einsetzbar.
Ergebnis im Bericht:
> Artikelbericht: Buchungsgruppe zur Anzeige auswählbar anbieten

- SL/Controller/Order.pm
Grund: Im Verkaufsbeleg können in den Bemerkungen Dinge stehen, welche den Lieferanten im Einkauf nichts angehen oder verwirren. Daher sollen die Bemerkungen beim Erzeugen eines EK-Beleges aus einem VK-Beleg nicht übernommen werden.
Ich habe das nun für die Bemerkungen und die internen Bemerkungen gemacht.
> Lösche Bemerkungen beim Workflow Lieferantenanfrage/-auftrag von VK zu EK

- SL/DB/Helper/DisplayableNamePreferences.pm
- SL/DB/Part.pm
Um im Part Picker oder der Schnellsuche nach der partsgroup suchen zu können, ist es sinnvoll, eine getter-Funktionen zu übergeben.
Andernfalls müssten wir eine getter-Funktion in S:D:Parts einbauen, z.B. get_partsgroup und dann den namensgleichen Ersetzungsstring <%get_partsgroup%> als Anzeigenamen einstellen. Diese Namensgebung scheint für die Nutzeroberfläche nicht elegant.
> DisplayableNamePreferences: partsgroup in Schnellsuche und Part Picker eingebaut

- SL/DB/Invoice.pm
Ist noch nicht aufgefallen:
In der Konsole:
```
my $inv = SL::DB::Manager::Invoice->find_by(id => 14687);
re.pl(main):040:0>  $inv->dunnings
Runtime error: 'Could not load SL::DB::Dunning objects with key trans_id = '14687' - Invalid with_objects or require_objects argument: no foreign key or relationship named 'dunnings' found in Rose::DB::Object::Manager at /usr/share/perl5/Rose/DB/Object/Manager.pm line 904.
```
> S:D:Invoice->dunnings lieferte Fehlermeldung, durch with_objects

- SL/Helper/Inventory.pm
- SL/X.pm
- templates/design40_webpages/wh/produce_assembly_error.html
Kleinigkeit aus Jans PR #584.
In der Fehlermeldung beim  Fertigen eines Erzeugnisses einen Link zur fehlenden Ware anbieten.
> 202509 feat show part produce assembly errors

- SL/Form.pm
Aus einem Kundenprojekt:
The previous behaviour was to return undef, which was not checked at the call-site. This left the user with no preset email text, whatsoever, providing no hint which setting is missing.
Now, we just leave out the greeting if none is set, which gives the user a higher chance to spot the missing translation.
I looked into reordering the settings (greetings first, then preset email texts later, but the sorting in the template makes this not easy, so we do without.
> S:Form: generate email body, even if salutation_general is unset

- SL/DO.pm
- SL/IS.pm
- SL/OE.pm
- bin/mozilla/io.pl
- js/kivi.Order.js
- templates/design40_webpages/order/tabs/_row.html
- templates/design40_webpages/order/tabs/_second_row.html
Diese Änderung bewirkt, dass beim Bearbeiten von Aufträgen in der Positionstabelle anstelle der Nummerierung von 1 bis n die Positionen wie im Ausdruck nummeriert werden. Der Unterschied wird sichtbar, sobald Zwischensummen verwendet werden. (Start/Stopp des Unterkapitels) Die Nummerierung wird aktualisiert, sobald die Einstellung der Zwischensumme an einer Position geändert wird.
Ebenso orientiert sich das "Artikel einfügen über Pos." an der Nummerierung mit Kapitelbildung.
Hier zur Illustration:
getestet (nur mit design 4.0):
- Nummerierung wird in Angeboten, Aufträgen angezeigt wie im PDF-Ausdruck via LaTeX
- Artikel hinzufügen über Pos. klappt
- Umordnen der Artikel per drag-and-drop klappt
Mir ist nicht klar:
- Gibt es bei der Nummerierung Wechselwirkungen mit Sortimenten oder …
> Angebote, Aufträge bearbeiten: zeige Positionsnummern mit Kapitelbildung (Zwischensumme)

- SL/DB/Helper/ZUGFeRD.pm
Ein Teil von #593 . Hier nur die Fehlerbehebung, ohne Anpassung der Fehlerbehandlung.
Die Manager-Klasse hat keine eigene Modul-Datei.
> ZUGFeRD: require für S:D:GenericTranslation, nicht für Manager davon.

- SL/Controller/AccTrans.pm
- templates/design40_webpages/acc_trans/no_data.html
Aus einem Kundenprojekt:
Returning an empty response of type application/json is not a proper error handling.
I booked an invoice with a net amount of 0 and searched a while to find out why the tab "bookings" is empty... This gives a clear hint.
> S:C:AccTrans: handle "no data" properly

- bin/mozilla/wh.pl
Zuvor passierte folgendes:
Beim Erzeugnis fertigen mit Menge 1,5 wurde in der Auswahl mehrdeutiger Lagerbestände (Chargennummer / MHD) zunächst 1,5 angezeigt, nach dem ersten Klick auf Erneuern jedoch 15. Dies liegt daran, dass im Form der formatierte Zahlenwert für die Menge durchgereicht wird. Dieser Commit setzt das konsequent um.
> fix: Erzeugnis fertigen mit fraktionaler Menge (Komma nicht ignorieren)
